# Generated by Django 4.2.26 on 2025-12-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, unique=True)),
                ('last_processed_line', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetWeightsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveBigIntegerField(db_index=True)),
                ('extrinsic_hash', models.CharField(max_length=66, unique=True)),
                ('netuid', models.PositiveIntegerField(db_index=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('weights_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-block_number'],
                'indexes': [models.Index(fields=['block_number', 'netuid'], name='core_setwei_block_n_d7074c_idx'), models.Index(fields=['netuid', 'address'], name='core_setwei_netuid_ff1213_idx')],
            },
        ),
        migrations.CreateModel(
            name='HyperparamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveBigIntegerField(db_index=True)),
                ('extrinsic_hash', models.CharField(max_length=66, unique=True)),
                ('call_function', models.CharField(db_index=True, max_length=100)),
                ('call_module', models.CharField(max_length=100)),
                ('netuid', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('call_args', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-block_number'],
                'indexes': [models.Index(fields=['block_number', 'netuid'], name='core_hyperp_block_n_3a854c_idx'), models.Index(fields=['call_function', 'netuid'], name='core_hyperp_call_fu_ccbb3f_idx')],
            },
        ),
    ]
