# Generated by Django 4.2.26 on 2025-12-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setweightsevent',
            name='events',
            field=models.JSONField(default=list),
        ),
    ]
