# Generated by Django 4.2.26 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_hyperparamevent_core_hyperp_call_fu_ccbb3f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extrinsic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("block_number", models.PositiveBigIntegerField(db_index=True)),
                ("extrinsic_hash", models.CharField(max_length=66, unique=True)),
                ("address", models.CharField(blank=True, db_index=True, max_length=66)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("call_function", models.CharField(db_index=True, max_length=100)),
                ("call_module", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("block_hash", models.CharField(blank=True, db_index=True, max_length=66)),
                (
                    "extrinsic_index",
                    models.PositiveIntegerField(blank=True, help_text="Index within the block", null=True),
                ),
                (
                    "block_timestamp",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="Block timestamp from Timestamp.Now", null=True
                    ),
                ),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("error_data", models.JSONField(blank=True, help_text="Error attributes if failed", null=True)),
                ("call_args", models.JSONField(default=dict, help_text="Call arguments from extrinsic")),
                ("signature", models.JSONField(blank=True, null=True)),
                ("nonce", models.PositiveBigIntegerField(blank=True, null=True)),
                ("tip_rao", models.BigIntegerField(blank=True, help_text="Tip in rao", null=True)),
                ("events", models.JSONField(default=list, help_text="Events associated with this extrinsic")),
                ("netuid", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "extrinsics",
                "ordering": ["-block_number", "-extrinsic_index"],
            },
        ),
        migrations.AddIndex(
            model_name="extrinsic",
            index=models.Index(fields=["block_number", "extrinsic_index"], name="extrinsics_block_n_18b40f_idx"),
        ),
        migrations.AddIndex(
            model_name="extrinsic",
            index=models.Index(fields=["block_hash"], name="extrinsics_block_h_00ef7f_idx"),
        ),
        migrations.AddIndex(
            model_name="extrinsic",
            index=models.Index(fields=["address", "block_number"], name="extrinsics_address_5b08c8_idx"),
        ),
        migrations.AddIndex(
            model_name="extrinsic",
            index=models.Index(
                fields=["call_module", "call_function", "success"], name="extrinsics_call_mo_1a7e2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extrinsic",
            index=models.Index(fields=["netuid", "call_function"], name="extrinsics_netuid_ab6e00_idx"),
        ),
    ]
