# Generated by Django 4.2.26 on 2025-12-11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_extrinsic"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="extrinsic",
            new_name="extrinsics_block_n_9a1f3e_idx",
            old_name="extrinsics_block_n_18b40f_idx",
        ),
        migrations.RenameIndex(
            model_name="extrinsic",
            new_name="extrinsics_block_h_7ae207_idx",
            old_name="extrinsics_block_h_00ef7f_idx",
        ),
        migrations.RenameIndex(
            model_name="extrinsic",
            new_name="extrinsics_address_653e67_idx",
            old_name="extrinsics_address_5b08c8_idx",
        ),
        migrations.RenameIndex(
            model_name="extrinsic",
            new_name="extrinsics_call_mo_837e16_idx",
            old_name="extrinsics_call_mo_1a7e2f_idx",
        ),
        migrations.RenameIndex(
            model_name="extrinsic",
            new_name="extrinsics_netuid_056ebb_idx",
            old_name="extrinsics_netuid_ab6e00_idx",
        ),
    ]
