# Generated by Django 4.2.26 on 2025-12-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_index_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="hyperparamevent",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, help_text="Block timestamp", null=True),
        ),
        migrations.AddField(
            model_name="setweightsevent",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, help_text="Block timestamp", null=True),
        ),
    ]
