# Generated by Django 4.2.26 on 2026-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubnetWebhook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("netuid", models.PositiveIntegerField(db_index=True)),
                ("url", models.URLField(max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subnet_webhooks",
                "unique_together": {("netuid", "url")},
            },
        ),
    ]
