# Generated by Django 4.2.26 on 2025-12-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("number", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("dump_started_at", models.DateTimeField(blank=True, null=True)),
                ("dump_finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "metagraph_block",
            },
        ),
        migrations.CreateModel(
            name="Coldkey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coldkey", models.CharField(max_length=66, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "metagraph_coldkey",
            },
        ),
        migrations.CreateModel(
            name="EvmKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("evm_address", models.CharField(max_length=42, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "metagraph_evm_key",
            },
        ),
        migrations.CreateModel(
            name="Hotkey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hotkey", models.CharField(max_length=66, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "coldkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hotkeys", to="metagraph.coldkey"
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_hotkey",
            },
        ),
        migrations.CreateModel(
            name="Neuron",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.PositiveIntegerField()),
                ("first_seen_block", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "evm_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="neurons",
                        to="metagraph.evmkey",
                    ),
                ),
                (
                    "hotkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="neurons", to="metagraph.hotkey"
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_neuron",
            },
        ),
        migrations.CreateModel(
            name="Subnet",
            fields=[
                ("netuid", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_hotkey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_subnets",
                        to="metagraph.hotkey",
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_subnet",
            },
        ),
        migrations.CreateModel(
            name="NeuronSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.PositiveIntegerField()),
                ("axon_address", models.CharField(blank=True, max_length=255)),
                (
                    "total_stake",
                    models.DecimalField(decimal_places=0, default=0, help_text="Total stake in rao", max_digits=30),
                ),
                ("normalized_stake", models.FloatField(default=0.0)),
                ("rank", models.FloatField(default=0.0)),
                ("trust", models.FloatField(default=0.0)),
                (
                    "emissions",
                    models.DecimalField(decimal_places=0, default=0, help_text="Emissions in rao", max_digits=30),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_validator", models.BooleanField(default=False)),
                ("is_immune", models.BooleanField(default=False)),
                ("has_any_weights", models.BooleanField(default=False)),
                ("neuron_version", models.PositiveIntegerField(blank=True, null=True)),
                ("block_at_registration", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neuron_snapshots",
                        to="metagraph.block",
                    ),
                ),
                (
                    "neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="metagraph.neuron"
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_neuron_snapshot",
            },
        ),
        migrations.AddField(
            model_name="neuron",
            name="subnet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="neurons", to="metagraph.subnet"
            ),
        ),
        migrations.CreateModel(
            name="MetagraphDump",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("netuid", models.PositiveIntegerField()),
                ("epoch_position", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metagraph_dumps",
                        to="metagraph.block",
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_dump",
            },
        ),
        migrations.CreateModel(
            name="MechanismMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mech_id", models.PositiveIntegerField()),
                ("incentive", models.FloatField(default=0.0)),
                ("dividend", models.FloatField(default=0.0)),
                ("consensus", models.FloatField(default=0.0)),
                ("validator_trust", models.FloatField(default=0.0)),
                ("weights_sum", models.FloatField(default=0.0)),
                ("last_update", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanism_metrics",
                        to="metagraph.neuronsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_mechanism_metrics",
            },
        ),
        migrations.CreateModel(
            name="Collateral",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=0, help_text="Collateral amount in rao", max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="collaterals", to="metagraph.block"
                    ),
                ),
                (
                    "source_neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_collateral",
                        to="metagraph.neuron",
                    ),
                ),
                (
                    "target_neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_collateral",
                        to="metagraph.neuron",
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_collateral",
            },
        ),
        migrations.CreateModel(
            name="Bond",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mech_id", models.PositiveIntegerField()),
                ("bond", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bonds", to="metagraph.block"
                    ),
                ),
                (
                    "source_neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_bonds",
                        to="metagraph.neuron",
                    ),
                ),
                (
                    "target_neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_bonds",
                        to="metagraph.neuron",
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_bond",
            },
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mech_id", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="weights", to="metagraph.block"
                    ),
                ),
                (
                    "source_neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_weights",
                        to="metagraph.neuron",
                    ),
                ),
                (
                    "target_neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_weights",
                        to="metagraph.neuron",
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_weight",
                "indexes": [
                    models.Index(fields=["block", "source_neuron"], name="metagraph_w_block_i_742f8c_idx"),
                    models.Index(fields=["block", "target_neuron"], name="metagraph_w_block_i_210f72_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="weight",
            constraint=models.UniqueConstraint(
                fields=("source_neuron", "target_neuron", "block", "mech_id"), name="unique_weight"
            ),
        ),
        migrations.AddIndex(
            model_name="neuronsnapshot",
            index=models.Index(fields=["block"], name="metagraph_n_block_i_e0bb78_idx"),
        ),
        migrations.AddIndex(
            model_name="neuronsnapshot",
            index=models.Index(
                condition=models.Q(("is_validator", True)), fields=["block", "neuron"], name="idx_validator_snapshots"
            ),
        ),
        migrations.AddConstraint(
            model_name="neuronsnapshot",
            constraint=models.UniqueConstraint(fields=("neuron", "block"), name="unique_neuron_block"),
        ),
        migrations.AddIndex(
            model_name="neuron",
            index=models.Index(fields=["subnet", "uid"], name="metagraph_n_subnet__b307c5_idx"),
        ),
        migrations.AddConstraint(
            model_name="neuron",
            constraint=models.UniqueConstraint(fields=("hotkey", "subnet"), name="unique_hotkey_subnet"),
        ),
        migrations.AddConstraint(
            model_name="metagraphdump",
            constraint=models.UniqueConstraint(fields=("netuid", "block"), name="unique_metagraph_dump"),
        ),
        migrations.AddIndex(
            model_name="mechanismmetrics",
            index=models.Index(fields=["snapshot"], name="metagraph_m_snapsho_2f7d15_idx"),
        ),
        migrations.AddConstraint(
            model_name="mechanismmetrics",
            constraint=models.UniqueConstraint(fields=("snapshot", "mech_id"), name="unique_snapshot_mech"),
        ),
        migrations.AddIndex(
            model_name="collateral",
            index=models.Index(fields=["source_neuron", "block"], name="metagraph_c_source__3f68e9_idx"),
        ),
        migrations.AddIndex(
            model_name="collateral",
            index=models.Index(fields=["target_neuron", "block"], name="metagraph_c_target__3dafd1_idx"),
        ),
        migrations.AddConstraint(
            model_name="collateral",
            constraint=models.UniqueConstraint(
                fields=("source_neuron", "target_neuron", "block"), name="unique_collateral"
            ),
        ),
        migrations.AddIndex(
            model_name="bond",
            index=models.Index(fields=["block", "source_neuron"], name="metagraph_b_block_i_ac8e94_idx"),
        ),
        migrations.AddIndex(
            model_name="bond",
            index=models.Index(fields=["block", "target_neuron"], name="metagraph_b_block_i_667861_idx"),
        ),
        migrations.AddConstraint(
            model_name="bond",
            constraint=models.UniqueConstraint(
                fields=("source_neuron", "target_neuron", "block", "mech_id"), name="unique_bond"
            ),
        ),
    ]
