# Generated by Django 4.2.26 on 2026-04-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metagraph", "0004_add_dividend_apy_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="block",
            index=models.Index(fields=["timestamp"], name="metagraph_b_timesta_78b7f4_idx"),
        ),
        migrations.AddIndex(
            model_name="neuronsnapshot",
            index=models.Index(
                condition=models.Q(("is_validator", True)),
                fields=["neuron", "block"],
                name="idx_validator_snaps_by_neuron",
            ),
        ),
        migrations.AddIndex(
            model_name="neuronsnapshot",
            index=models.Index(fields=["-total_stake"], name="metagraph_n_total_s_065941_idx"),
        ),
    ]
