# Generated by Django 5.2.16 on 2026-08-03 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metagraph", "0014_retention_miner_block_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaEpoch",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="meta_epoch",
                        serialize=False,
                        to="metagraph.block",
                    ),
                ),
            ],
            options={
                "verbose_name": "meta epoch",
                "verbose_name_plural": "meta epochs",
                "db_table": "metagraph_meta_epoch",
            },
        ),
        migrations.CreateModel(
            name="SubnetBurn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_block_number",
                    models.PositiveBigIntegerField(help_text="Subnet epoch-start block the values were computed from."),
                ),
                (
                    "burn",
                    models.FloatField(
                        help_text="Owner-coldkey share of subnet incentive, averaged across mechanisms (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "superburn",
                    models.FloatField(
                        help_text="Superburn-coldkey share of subnet incentive, averaged across mechanisms (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "meta_epoch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="burns", to="metagraph.metaepoch"
                    ),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="burns", to="metagraph.subnet"
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_subnet_burn",
                "indexes": [models.Index(fields=["meta_epoch", "subnet"], name="idx_subnet_burn_epoch")],
                "constraints": [
                    models.UniqueConstraint(fields=("subnet", "meta_epoch"), name="unique_subnet_burn"),
                    models.CheckConstraint(
                        condition=models.Q(("burn__gte", 0.0), ("burn__lte", 1.0)), name="subnet_burn_between_0_and_1"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("superburn__gte", 0.0), ("superburn__lte", 1.0)),
                        name="subnet_superburn_between_0_and_1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubnetEmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emission_enabled", models.BooleanField()),
                (
                    "meta_epoch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emissions", to="metagraph.metaepoch"
                    ),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emissions", to="metagraph.subnet"
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_subnet_emission",
                "indexes": [models.Index(fields=["meta_epoch", "subnet"], name="idx_subnet_emission_epoch")],
                "constraints": [
                    models.UniqueConstraint(fields=("subnet", "meta_epoch"), name="unique_subnet_emission")
                ],
            },
        ),
    ]
