# Generated by Django 4.2.26 on 2026-01-14 13:28
"""
State-only migration to update index names in Django's state.

The database indexes may have different names (or not exist), so we only
update Django's internal state without touching the database.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrinsics', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='extrinsic',
                    new_name='extrinsics_block_n_8a4c59_idx',
                    old_name='extrinsics_block_n_callf_idx',
                ),
                migrations.RenameIndex(
                    model_name='extrinsic',
                    new_name='extrinsics_address_5b3b9b_idx',
                    old_name='extrinsics_address_callf_idx',
                ),
            ],
            database_operations=[],  # No database changes - indexes may not exist with these names
        ),
    ]
