# Generated by Django 4.2.26 on 2026-04-01 11:29

from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor):
    """Rename the created_at index only if the old name exists."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_indexes WHERE indexname = %s",
            ["extrinsics_created_f0a498_idx"],
        )
        if cursor.fetchone():
            cursor.execute("ALTER INDEX extrinsics_created_f0a498_idx RENAME TO extrinsics_created_c6a814_idx")


class Migration(migrations.Migration):
    dependencies = [
        ("extrinsics", "0005_add_block_timestamp_index"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_index_if_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="extrinsic",
                    new_name="extrinsics_created_c6a814_idx",
                    old_name="extrinsics_created_f0a498_idx",
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="extrinsic",
            index=models.Index(fields=["call_function", "block_timestamp"], name="extrinsics_call_fu_dba940_idx"),
        ),
    ]
