# Generated by Django 4.2.26 on 2026-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extrinsics", "0011_add_call_lookup_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtensorerrorcode",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
